### ISSUE TITLE
pgt_created_at overriding created_at timestamp for tests

### ISSUE THREAD

**Issue by michaelrabie** [jeremyevans/sequel_postgresql_triggers#11]
I'm running into an issue where I'm trying to create a test that ignores all models created more than a day ago. The issue that I am having is that I cannot override the `created_at` timestamp to be anything other than the current time. 

For example: 
```
ModelName.create(
      user_id: 1,
      created_at: 1.year.ago
    )
```
will contain a created_at timestamp of the current time. And time freezers like `Timecop` doesn't work since the timestamp is created on the database level. 

Is there anything I can do to be able to pass in a created_at timestamp?

**Comment by jeremyevans** [comment]
You would probably have to disable the trigger on the table , run that code, then enable the trigger afterward.  See https://www.postgresql.org/docs/current/static/sql-altertable.html for the SQL for enabling/disabling triggers.

**Comment by michaelrabie** [comment]
Thanks, this does the trick!
