### ISSUE TITLE
The triggers are not pg_dump-friendly

### ISSUE THREAD

**Issue by x-yuri** [jeremyevans/sequel_postgresql_triggers#14]
`docker-compose.yml`:

```yaml
services:
  app:
    build: .
    command: sleep infinity
    init: true
    volumes:
      - .:/app
  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  db2:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
```

`Dockerfile`:

```dockerfile
FROM ruby:3.2.2-alpine3.18
RUN apk add build-base postgresql15-dev
WORKDIR /app
COPY Gemfile .
RUN bundle install
```

`Gemfile`:

```rb
source "https://rubygems.org"
gem 'sequel', '5.70.0'
gem 'pg'
gem 'sequel_postgresql_triggers', '1.5.0'
```

`migrations/1_create_tables.rb`:

```rb
Sequel.migration do
  change do
    create_table(:users) do
      primary_key :id
      String :name
    end
    create_table(:images) do
      primary_key :id
      foreign_key :user_id, :users
      String :filename
      TrueClass :deleted
    end
  end
end
```

`migrations/2_add_trigger.rb`:

```rb
Sequel.migration do
  up do
    extension :pg_triggers
    add_column :users, :image_count, :Integer, default: 0
    pgt_sum_cache(:users,
                  :id,
                  :image_count,
                  :images,
                  :user_id,
                  Sequel.case({ deleted: 0 }, 1),
                  function_name: :users_set_image_count,
                  trigger_name: :set_image_count)
  end
  down do
    drop_trigger(:users, :set_image_count)
    drop_function(:users_set_image_count)
    drop_column :users, :image_count
  end
end
```

```
$ docker-compose up -d
$ docker-compose exec app sequel -m migrations postgres://postgres@db
$ docker-compose exec db psql -U postgres \
    -c "insert into users (name) values ('John')"
$ docker-compose exec db psql -U postgres \
    -c "insert into images (user_id, filename) values (1, 'a.png')"
$ docker-compose exec -T db pg_dump -U postgres -s \
    | docker-compose exec -T db2 psql -U postgres
$ docker-compose exec -T db pg_dump -U postgres -a \
    | docker-compose exec -T db2 psql -U postgres
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
COPY 1
ERROR:  relation "users" does not exist
LINE 1: UPDATE "users" SET "image_count" = "image_count" + (CASE WHE...
               ^
QUERY:  UPDATE "users" SET "image_count" = "image_count" + (CASE WHEN NEW."deleted" THEN 0 ELSE 1 END) WHERE "id" = NEW."user_id"
CONTEXT:  PL/pgSQL function public.users_set_image_count() line 6 at SQL statement
COPY images, line 1: "1	1	a.png	\N"
COPY 1
 setval 
--------
      1
(1 row)

 setval 
--------
      1
(1 row)
```

If I migrate schema and data in one go, it succeeds. Why do I migrate schema first? Because often it's already there, because migrations has been applied. And what's left is to copy data.

Why does it fail? Apparently because `pg_dump` sets `search_path` to `''`:

```
$ docker-compose exec -T db pg_dump -U postgres -s
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
```

Should it be fixed? I'm not sure. On one hand you probably don't want to execute triggers when copying data (and as such want to use `--disable-triggers`, with which it succeeds). But if you copy partial data, you do. And the fact that it fails can remind you about this. Although the message is not too revealing. But then, the best you can achieve in terms of partial imports with `pg_dump` is probably to not import some tables, and then triggers won't help.

On a side note, I wonder if `drop_(trigger|function)` can be avoided (a `change` migration). And with an expression (`Sequel.case({ deleted: 0 }, 1)`) it fails to autogenerate the function name.

**Comment by jeremyevans** [comment]
Thanks for bringing this to my attention.  I don't think this is a bug; it's a general issue when using triggers in PostgreSQL, not specific to the triggers created by sequel_postgresql_triggers.  It's probably worth documenting in the README.

> On a side note, I wonder if drop_(trigger|function) can be avoided (a change migration). And with an expression (Sequel.case({ deleted: 0 }, 1)) it fails to autogenerate the function name.

The `pgt_*` functions are not reversible, so you need to use `up`/`down` and not `change`. Usually when I'm using sequel_postgresql_triggers, I'm doing other things that are not reversible anyway, so this isn't something I plan to work on.  I'd guess than about 80% of the migrations used in my production applications use `up`/`down` and not `change` as they call methods the migration reverser does not support.
