### ISSUE TITLE
Feature: Migration `down` support for triggers that have been created with sequel_postgresql_triggers

### ISSUE THREAD

**Issue by TSMMark** [jeremyevans/sequel_postgresql_triggers#7]
There is no nice DSL for dropping the functions and/or triggers that are created using this plugin. At Vydia, we would like our migrations to be reversible when possible. @jeremyevans I would be happy to work on this if you think it's a good idea.

**Comment by jeremyevans** [comment]
Personally, I don't think it is worth the effort.  I find that there are a fairly low percentage of migrations in my own applications that are reversible, and all of them are fairly simple.  That being said, I believe it is possible to support this without API changes to Sequel, so I'm willing to consider a patch as long it contains appropriate tests.

**Comment by jeremyevans** [comment]
As this doesn't seem to be a bug, I'm going to close this now.  If you would like to see this proposed feature supported, please submit a pull request.

**Comment by TSMMark** [comment]
Okay. I may hit you up with PR if I have some extra time this weekend.
