### ISSUE TITLE
Improve documentation with a list of steps to get started

### ISSUE THREAD

**Issue by mikeyhew** [jeremyevans/sequel_postgresql_triggers#8]
This project could use a "Quick Start" guide in the readme. At this point, it's not very obvious how to use it - I can guess that you include the gem in you Gemfile, but then what? Is pgt_created_at a schema modification method that you can call during migrations?

I can probably figure out how to use it by reading through the source code and seeing what methods are defined, but if you make it more clear what to do with this gem in the documentation, you would probably get more people using and contributing to it. Just my two cents :)

**Comment by jeremyevans** [comment]
I agree, the current README is lacking in this regard.  I'll work on improving it shortly.
